require 'CleevioFastlane'
import(CleevioFastlane.path)

CONFIG = FastlaneConfig.new(
    unit_tests_build_configuration: "Debug",
    deployments: {
        :devel => [
        	SPMFramework.new()
        ]
    }
)
